### ISSUE TITLE
VolunteerForm

### ISSUE THREAD

**Issue by Meryalvhe** [IgrowkerTraining/i004-pawsome-front#22]

**Comment by Nico235711** [comment]
finished voluteerForm

**Comment by Meryalvhe** [comment]
Hola Nico, 
Revisando el volunteer form, solo agregar hacer el cambio de color de los inputs, que el figma son blancos y en los tuyos completamente gris. 
Adicionalmente, yo le quitaría el margin al input para que no esté tan separado. 
Finalmente, te hace falta un botón para enviar el formulario. 

Gracias!

**Comment by Nico235711** [comment]
Gracias mery desp realizo los cambios

**Comment by Meryalvhe** [comment]
Hola Nico, 

He revisado tus cambio y solo sería necesario hacer el botón ronuded, porque los botones no son cuadrados y luego el color debe ser el "#6AB4A8"

Gracias!
