### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by patrigarcia** [IgrowkerTraining/i004-pawsome-front#3]
Crear el componente de Register para permitir que los usuarios se registren en la aplicación. Este formulario debe alinearse con el diseño proporcionado.
Requisitos:
Formulario de registro: Incluir campos para correo electrónico, contraseña, y confirmación de contraseña. Validación de campos: Validar el formato del correo electrónico, que las contraseñas coincidan y cumplan con los requisitos de seguridad. Estilos: Asegurarse de que el componente respete el diseño de UI. Manejo de Estados: Incluir estados de carga y error para brindar feedback en el proceso de registro.

**Comment by Melsalome** [comment]
Diseño de formulario
Validación de inputs
Contraseñas que coincidan
Lógica conexión con el back -
Estados de carga y error
READY FOR QA
